version: "3"
services:
  app:
    # image: ghcr.io/totodore/laura-api:latest
    container_name: garage-bot
    build: .
    tty: true
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - "web"
    depends_on:
      - db
    links: 
      - db
  db:
    image: mysql
    container_name: garage-bot-db
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    expose:
      - 3306
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - "web"

networks:
  web:
    external: true

volumes:
  mysqldata: